export const RAI_VERSION = "0.0.0";

export * from "./types.js";
export { resolveConfig, DEFAULT_CONFIG } from "./config/resolve.js";
export { analyzeRepo } from "./engine/pipeline.js";
export { runBackfill } from "./engine/backfill.js";
export type { BackfillAnalyzeResult, BackfillCommitResult, BackfillInput, BackfillResult } from "./engine/backfill.js";
export { createSession, Session } from "./mcp/tools.js";
export { buildMcpServer, serveStdio, readSources } from "./mcp/server.js";
export type { SourceFile } from "./parse/graph-build.js";
export { sharedExtraction, RULE_ID as SHARED_EXTRACTION_RULE_ID } from "./analyzers/shared-extraction.js";
export { renderCoupling, RULE_ID as RENDER_COUPLING_RULE_ID } from "./analyzers/render-coupling.js";
export { overAbstraction, RULE_ID as OVER_ABSTRACTION_RULE_ID } from "./analyzers/over-abstraction.js";
export { hookTopology, RULE_ID as HOOK_TOPOLOGY_RULE_ID } from "./analyzers/hook-topology.js";
export { boundaryViolation, RULE_ID as BOUNDARY_VIOLATION_RULE_ID } from "./analyzers/boundary-violation.js";
export type { Analyzer, AnalyzerResult, AnalysisContext, BoundaryRule, TypeInfo, TypeResolver } from "./analyzers/analyzer.js";
export { AnalyzerRegistry, createDefaultAnalyzerRegistry } from "./analyzers/registry.js";
export type { RegistryFactory, RegistryFactoryInput, SessionOpts } from "./mcp/tools.js";
export { buildSharedExtractionProposal } from "./codemod/proposal.js";
export type { SharedExtractionProposal, ProposalRefusalReason, ProposalRisk, ProposalRiskLevel, ProposalRiskReason } from "./codemod/proposal.js";
export { mayExecuteCodemod } from "./codemod/capability-gate.js";
export type { CodemodGateContext, CodemodGateRefusalReason, CodemodGateResult } from "./codemod/capability-gate.js";
export { previewSharedExtractionPatch } from "./codemod/dry-run.js";
export type { DryRunPatchInput, DryRunPatchPreview, DryRunRefusalReason } from "./codemod/dry-run.js";
export { runApplyRefactorPipeline } from "./codemod/apply-pipeline.js";
export type { ApplyPipelineInput, ApplyPipelineResult, ApplyWorkspace, VerificationCommand, VerificationResult, VerificationStage } from "./codemod/apply-pipeline.js";
export { createGitWorkspace } from "./codemod/git-workspace.js";
export type { GitWorkspaceOpts } from "./codemod/git-workspace.js";
export { CodemodProofStore } from "./memory/codemod-proof-store.js";
export type { CodemodProofInput, CodemodProofRow, CodemodProofStatus } from "./memory/codemod-proof-store.js";
export { explainTerm, glossaryEntries } from "./explainability/glossary.js";
export type { GlossaryEntry } from "./explainability/glossary.js";
export { explainFinding } from "./explainability/explain.js";
export { findingFileRefs, findingMatchesFile } from "./explainability/file-refs.js";
export type { FindingFileRef } from "./explainability/file-refs.js";
